export const giftLocators = {
    giftCardAmount: (amount) => `//div[normalize-space(text())='$${amount}']`,
    deliveryMethod: (method) => `//div[normalize-space(text())='${method}']`,
    senderFullNameInput: `//label[text()='Full Name']/following-sibling::input`,
    senderEmailInput: `//label[text()='Email']/following-sibling::input`,
    recepientFullNameInput: `//label[text()="Recipient's Name"]/following-sibling::input`,
    recepientEmailInput: `//label[text()="Recipient's Email"]/following-sibling::input`,
    messageTextArea: `//textarea[contains(@class, 'message')]`,
    sendingTime: (text) => `//button[text()='${text}']`,
    continueButton: `//button//span[text()='Continue to Payment']`,
    cardNumberInput: `#Field-numberInput`,
    cardExpiryInput: `#Field-expiryInput`,
    cardCvvInput: `#Field-cvcInput`,
    purchaseButton: `#submit`,
    confirmationMessage: `//h1[text()='Your gift card purchase is complete!']/following-sibling::p/span`,
    orderCompleteMessage: `//h1[text()='Your gift card purchase is complete!']`,
    datePicker: `//input[@aria-label='Datepicker input']`,
    nextDayButton: `//div[@aria-selected='true']/following-sibling::div`,
    corporateGiftLink: `(//a[text()='corporate sales'])[1]`,
    inquiriesText: `#lp-pom-text-93`,
    fieldWarning: (field) => `//label[text()="${field}"]/following-sibling::div`,
    otherAmountButton: `//label[text()=' Other']`,
    otherAmountInput: `//input[@type='number']`,
    otherAmountWarning: `//input[@type='number']/following-sibling::div`,
    cardNumberWarning: `#Field-numberError`,
    cardExpiryWarning: `#Field-expiryError`,
    cardCvvWarning: `#Field-cvcError`,
    selectCountry: `#Field-countryInput`,
    indiaText: `//option[@value="IN"]`,
  };
  